[pytest]
minversion = 6.0
addopts = -ra -q
testpaths = tests

# Custom test markers
markers =
    unit: quick unit tests
    full: full/integration tests
    impact: mark test as impacted by given files or symbols

